---
docker_compose_state: present

# NFS
nfs_host: "{{ hostvars['eggs']['ansible_host'] }}"
nfs_share: /mnt/farm/eggs
nfs_mountpoint: /mnt/eggs

# Cron
cron_state: present

# iSCSI
iscsi_host: "{{ hostvars['eggs']['ansible_host'] }}"
iscsi_target_name: dconfig2
iscsi_config_directory: /mnt/configs
