---
ansible_host: 192.168.1.180
ansible_user: root

# Pi host ip address
pi_host: 192.168.1.33
scripts_directory: /scripts

# Restic
backblaze_repo: "b2:eggs-restic-backup:/repo"
mountpoint: /mnt/tank/photos
restic_directory: /restic
