---
galaxy_info:
  author: Ricky Dua
  description: >-
    Install docker and docker-compose on Debian/Ubuntu
    with docker-compose.yml and .env provided

  license: license (BSD, MIT)

  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - focal
        - bionic

  min_ansible_version: "2.1"

  galaxy_tags: []

dependencies: []
